CREATE TABLE USERS (
        USERNAME VARCHAR(10) NOT NULL,
        PASSWORD VARCHAR(30) NOT NULL,
        ENABLED SMALLINT DEFAULT '1',
        PRIMARY KEY (USERNAME)
);

CREATE TABLE AUTHORITIES (
        USERNAME VARCHAR(10) NOT NULL,
        AUTHORITY VARCHAR(30) NOT NULL,
        FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

insert into USERS (USERNAME, PASSWORD) values ('admin1','ad');
insert into AUTHORITIES (USERNAME, AUTHORITY) values ('admin1','ROLE_USER');
